### ISSUE TITLE
Quick question regarding prognn

### ISSUE THREAD

**Issue by zeyuyun1** [DSE-MSU/DeepRobust#63]
https://github.com/DSE-MSU/DeepRobust/blob/067f1e1ea407e89df068eff65835392ea79b5b75/deeprobust/graph/defense/prognn.py#L181

What's the idea behind this line? Why would the nuclear loss be zeroed before taking the backpropagation step?

**Comment by ChandlerBang** [comment]
Hi, if you take a look at the conditional statements
https://github.com/DSE-MSU/DeepRobust/blob/067f1e1ea407e89df068eff65835392ea79b5b75/deeprobust/graph/defense/prognn.py#L182-L185

you will find that the `loss_nuclear` is 0 only when `args.beta==0`(the coefficient controlling the contribution of low rank). Otherwise, `loss_nuclear` will be replaced by `prox_operators.nuclear_norm`.

**Comment by zeyuyun1** [comment]
Thanks for the quick reply!
